name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  stack:
    name: Stack
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        resolver:
        # Missing some packages now
        #- "--resolver nightly"
        - lts-18.16 # Win32 issue
        - lts-16
        stack-yaml:
        - stack.yaml
        - stack-new-time.yaml
        exclude:
        - resolver: lts-16
          stack-yaml: stack-new-time.yaml
        - os: windows-latest
          stack-yaml: stack-new-time.yaml

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            stack --version
            stack test --fast --no-terminal --stack-yaml=${{ matrix.stack-yaml }} --resolver=${{ matrix.resolver }}
